### ISSUE TITLE
[BUG] After update ngx-stripe to 15.x.x, error accoured

### ISSUE THREAD

**Issue by 4i-helpynet** [richnologies/ngx-stripe#197]
**Describe the bug**
On serve:
Error: node_modules/ngx-stripe/lib/services/stripe-instance.class.d.ts:105:5 - error TS2416: Property 'paymentRequest' in type 'StripeInstance' is not assignable to the same property in base type 'StripeServiceInterface'.
  Type '(options: PaymentRequestOptions) => PaymentRequest | undefined' is not assignable to type '(options: PaymentRequestOptions) => PaymentRequest'.
    Type 'PaymentRequest | undefined' is not assignable to type 'PaymentRequest'.
      Type 'undefined' is not assignable to type 'PaymentRequest'.

105     paymentRequest(options: PaymentRequestOptions): PaymentRequest | undefined;
        ~~~~~~~~~~~~~~
Error: node_modules/ngx-stripe/lib/services/stripe.service.d.ts:109:5 - error TS2416: Property 'paymentRequest' in type 'StripeService' is not assignable to the same property in base type 'StripeServiceInterface'.
  Type '(options: PaymentRequestOptions) => PaymentRequest | undefined' is not assignable to type '(options: PaymentRequestOptions) => PaymentRequest'.
    Type 'PaymentRequest | undefined' is not assignable to type 'PaymentRequest'.
      Type 'undefined' is not assignable to type 'PaymentRequest'.

109     paymentRequest(options: PaymentRequestOptions): PaymentRequest | undefined;

**To Reproduce**
Steps to reproduce the behavior:
Update ngx-stripe from 14.x to the newest version

**Comment by richnologies** [comment]
Hi @4i-helpynet, is it possible this is a duplicate of https://github.com/richnologies/ngx-stripe/issues/195? 

Can you confirm me exactly which version are you using?

**Comment by 4i-helpynet** [comment]
Sorry, yes, igore this, I'll try to fix it with #195

**Comment by richnologies** [comment]
Hey @ranma42,

My bad, I only apply the change to `15.X.X` I will try to release a new v14 version today fixing this problem

**Comment by richnologies** [comment]
Hay @ranma42, sorry about the delay. Just publish a new version `14.3.1` that should fix this problem.

Please, let me know if that works for you

**Comment by shriyank-sensussoft** [comment]
` Property 'paymentRequest' in type 'StripeInstance' is not assignable to the same property in base type 'StripeServiceInterface'.`
@richnologies This error is still occurring in `14.3.1`

**Comment by dipankakalita** [comment]
What can we do @richnologies , I am unable to redeploy my site. Is there any solution?
![image](https://user-images.githubusercontent.com/68116094/215855904-e1b22d76-924d-431e-a14f-f1c9c5854dcc.png)

**Comment by richnologies** [comment]
So sorry guys. Just add anew version `14.3.2` Hopefully this one will fix it for good. 

Please let me know if it works for you

**Comment by ranma42** [comment]
I confirm that `14.3.1` does not fix the build issue, whereas after upgrading to `14.3.2` my app builds just fine 🚀 
Thank you!

**Comment by richnologies** [comment]
Thanks for the feeback @ranma42
