### ISSUE TITLE
[BUG] Property 'paymentRequest' in type 'StripeService' is not assignable to the same property in base type 'StripeServiceInterface'

### ISSUE THREAD

**Issue by selected-pixel-jameson** [richnologies/ngx-stripe#195]
**Describe the bug**
After updating my Angular project to 15.1.0 I'm getting the following error when trying to compile the project.
```
Error: node_modules/ngx-stripe/lib/services/stripe.service.d.ts:109:5 - error TS2416: Property 'paymentRequest' in type 'StripeService' is not assignable to the same property in base type 'StripeServiceInterface'.
  Type '(options: PaymentRequestOptions) => PaymentRequest | undefined' is not assignable to type '(options: PaymentRequestOptions) => PaymentRequest'.
    Type 'PaymentRequest | undefined' is not assignable to type 'PaymentRequest'.
      Type 'undefined' is not assignable to type 'PaymentRequest'.

109     paymentRequest(options: PaymentRequestOptions): PaymentRequest | undefined;
```

**To Reproduce**
Instal Angular 15.1.0 and ngx-stripe 15.0.0

**Expected behavior**
I expect my project to compile successfully.

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
This was working fine before I updated to Angular 15.1.0 and ngx-stripe 15.0.0.

**Comment by selected-pixel-jameson** [comment]
Note that if I disable "strict" compiling in my tsconfig.json this issue goes away.

**Comment by richnologies** [comment]
Good morning @selected-pixel-jameson,

Thanks for raising this problem, really appreciate it.

I've release a new version to npm `15.1.1` that I think it will fix the problem, but I did not have much time to test it. I'd really appreciate if you can confirm me if this fixes your problem. 

Regards,

R

**Comment by selected-pixel-jameson** [comment]
Issue has been resolved. Thank you!
